packages:
  - packages/*
  - playgrounds/*
  - examples/*
  - '!**/test/**'

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - svelte-preprocess

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@qtsurfer/*'