packages:
  - packages/*
  - playgrounds/*
  - examples/*
  - '!**/test/**'

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - svelte-preprocess

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@qtsurfer/*'
# Exclude Svelte packages from minimum release age temporalily to allow faster releases
  - '@sveltejs/*'
  - 'svelte'